name: Go Matrix Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
        go-version: ['1.20', '1.21']
        exclude:
          - os: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Prep modules
      run: |
        go mod init example.com/trash-levels && \
        go get github.com/gorilla/mux/ && \
        go get github.com/prometheus/client_golang/prometheus && \
        go get github.com/prometheus/client_golang/prometheus/promhttp
    - name: Build
      run: go build -v main.go
    - name: Latest-specific step
      if: matrix.os == 'ubuntu-latest'
      run: echo "Running on Ubuntu latest"
